<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro"
       name="youbot" >

  <!-- The following included files set up definitions of parts of the robot body -->
  <!-- misc common stuff -->
  <xacro:include filename="$(find description)/urdf/common.xacro" />
  <xacro:include filename="$(find description)/urdf/materials.urdf.xacro" />
  <!-- youbot base and rear platform -->
  <xacro:include filename="$(find description)/urdf/base.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/rear_platform_v2.urdf.xacro" />
  <!-- controller manager -->
  <xacro:include filename="$(find description)/urdf/ros_controller.urdf.xacro" />
  <!-- materials for visualization -->
  <xacro:include filename="$(find description)/urdf/material.urdf.xacro" />
  <!-- laser sensors -->
  <xacro:include filename="$(find description)/urdf/hokuyo_urg04_laser.urdf.xacro"/>
  <!-- kinect sensors -->
  <xacro:include filename="$(find description)/urdf/kinect_camera.urdf.xacro"/>
  <!-- sonar sensors -->
  <xacro:include filename="$(find description)/urdf/sonar_sensor.urdf.xacro"/>


  <!-- Now we can start using the macros included above to define the actual youbot -->

  <!-- standard youBot configuration -->
  <xacro:youbot_base name="base"/>

  <!-- Rear Platform -->
  <xacro:rear_platform_v2 name="rear_platform" parent="base_link">
    <origin xyz="0.12 -0.175 ${0.021 + 0.0062 + 0.025 + 0.012}" rpy="0 0 0" />  <!-- ${alignment with base top + nut height + spacer height + slide height } -->
  </xacro:rear_platform_v2>

  <!-- base laser front -->
  <xacro:hokuyo_urg04_laser name="base_laser_front" parent="base" ros_topic="scan_front" update_rate="10" min_angle="-1.57" max_angle="1.57">
    <origin xyz="0.3 0 -0.035" rpy="${M_PI} 0 0"/>
  </xacro:hokuyo_urg04_laser>

  <!-- base laser rear -->
  <xacro:hokuyo_urg04_laser name="base_laser_rear" parent="base" ros_topic="scan_rear" update_rate="10" min_angle="-1.57" max_angle="1.57" >
     <origin xyz="-0.3 0.0 -0.035" rpy="${M_PI} 0 ${M_PI}" />
  </xacro:hokuyo_urg04_laser>

  <!-- base kinect -->
  <xacro:kinect_camera name="base_kinect" parent="base_link"  >
     <origin xyz="0.11 0.0 0.12" rpy="0 0 0" />
  </xacro:kinect_camera>

  <!-- base sonar front -->
  <xacro:sonar_sensor name="base_sonar_front" parent="base_link" >
     <origin xyz="0.327 0.0 -0.015" rpy="0 0 0" />
  </xacro:sonar_sensor>

  <!-- base sonar rear -->
  <xacro:sonar_sensor name="base_sonar_rear" parent="base_link" >
     <origin xyz="-0.327 0.0 -0.015" rpy="0 0 ${M_PI}" />
  </xacro:sonar_sensor>

  <!-- base sonar left -->
  <xacro:sonar_sensor name="base_sonar_left" parent="base_link" >
     <origin xyz="0.0 0.16 -0.015" rpy="0 0 ${M_PI/2}" />
  </xacro:sonar_sensor>

  <!-- base sonar right -->
  <xacro:sonar_sensor name="base_sonar_right" parent="base_link" >
     <origin xyz="0.0 -0.16 -0.015" rpy="0 0 ${-M_PI/2}" />
  </xacro:sonar_sensor>  

</robot>
